-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    H_x_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_x_0_ce0 : OUT STD_LOGIC;
    H_x_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_x_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_x_1_ce0 : OUT STD_LOGIC;
    H_x_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_x_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_x_2_ce0 : OUT STD_LOGIC;
    H_x_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_x_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_x_3_ce0 : OUT STD_LOGIC;
    H_x_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_pred_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_3_ce0 : OUT STD_LOGIC;
    H_pred_3_we0 : OUT STD_LOGIC;
    H_pred_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    H_pred_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_0_ce0 : OUT STD_LOGIC;
    H_pred_0_we0 : OUT STD_LOGIC;
    H_pred_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    H_pred_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_1_ce0 : OUT STD_LOGIC;
    H_pred_1_we0 : OUT STD_LOGIC;
    H_pred_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    H_pred_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_2_ce0 : OUT STD_LOGIC;
    H_pred_2_we0 : OUT STD_LOGIC;
    H_pred_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_0_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_0_ce0 : OUT STD_LOGIC;
    A_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    A_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    A_3_ce0 : OUT STD_LOGIC;
    A_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_382_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_382_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_382_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_382_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_382_p_ce : OUT STD_LOGIC;
    grp_fu_386_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_386_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_386_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_386_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_386_p_ce : OUT STD_LOGIC;
    grp_fu_390_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_390_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_390_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_390_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_390_p_ce : OUT STD_LOGIC;
    grp_fu_394_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_394_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_394_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_394_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_394_p_ce : OUT STD_LOGIC;
    grp_fu_398_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_398_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_398_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_398_p_ce : OUT STD_LOGIC;
    grp_fu_402_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_402_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_402_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_402_p_ce : OUT STD_LOGIC;
    grp_fu_406_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_406_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_406_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_406_p_ce : OUT STD_LOGIC;
    grp_fu_410_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_410_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_410_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_410_p_ce : OUT STD_LOGIC );
end;


architecture behav of predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln45_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln45_fu_343_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_reg_461_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln48_reg_477_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln48_fu_353_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln48_reg_484_pp0_iter18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal bitcast_ln53_fu_388_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln53_4_fu_393_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul1_reg_503 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln53_1_fu_398_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln53_5_fu_403_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add1_reg_528 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul48_1_reg_533 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln53_2_fu_408_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln53_6_fu_413_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add53_1_reg_558 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul48_2_reg_563 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_pred_3_addr_reg_573 : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_3_addr_reg_573_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_3_addr_reg_573_pp0_iter14_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_3_addr_reg_573_pp0_iter15_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_3_addr_reg_573_pp0_iter16_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_3_addr_reg_573_pp0_iter17_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_3_addr_reg_573_pp0_iter18_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578 : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578_pp0_iter14_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578_pp0_iter15_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578_pp0_iter16_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578_pp0_iter17_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_0_addr_reg_578_pp0_iter18_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583 : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583_pp0_iter14_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583_pp0_iter15_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583_pp0_iter16_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583_pp0_iter17_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_1_addr_reg_583_pp0_iter18_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588 : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588_pp0_iter14_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588_pp0_iter15_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588_pp0_iter16_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588_pp0_iter17_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal H_pred_2_addr_reg_588_pp0_iter18_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal bitcast_ln53_3_fu_418_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln53_7_fu_423_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add53_2_reg_608 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul48_3_reg_613 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln48_fu_367_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal k_fu_80 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln45_fu_335_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_84 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln45_fu_303_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (7 downto 0);
    signal H_x_0_ce0_local : STD_LOGIC;
    signal A_0_ce0_local : STD_LOGIC;
    signal H_x_1_ce0_local : STD_LOGIC;
    signal A_1_ce0_local : STD_LOGIC;
    signal H_x_2_ce0_local : STD_LOGIC;
    signal A_2_ce0_local : STD_LOGIC;
    signal H_x_3_ce0_local : STD_LOGIC;
    signal A_3_ce0_local : STD_LOGIC;
    signal H_pred_2_we0_local : STD_LOGIC;
    signal bitcast_ln53_8_fu_428_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_pred_2_ce0_local : STD_LOGIC;
    signal H_pred_1_we0_local : STD_LOGIC;
    signal H_pred_1_ce0_local : STD_LOGIC;
    signal H_pred_0_we0_local : STD_LOGIC;
    signal H_pred_0_ce0_local : STD_LOGIC;
    signal H_pred_3_we0_local : STD_LOGIC;
    signal H_pred_3_ce0_local : STD_LOGIC;
    signal icmp_ln48_fu_315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln45_1_fu_329_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln32_fu_321_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component predict_kernel_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component predict_kernel_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component predict_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component predict_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter18_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln45_fu_297_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_76 <= add_ln48_fu_367_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_76 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln45_fu_297_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_84 <= add_ln45_fu_303_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_84 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln45_fu_297_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_80 <= select_ln45_fu_335_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_80 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                H_pred_0_addr_reg_578 <= zext_ln45_reg_461_pp0_iter11_reg(5 - 1 downto 0);
                H_pred_0_addr_reg_578_pp0_iter13_reg <= H_pred_0_addr_reg_578;
                H_pred_0_addr_reg_578_pp0_iter14_reg <= H_pred_0_addr_reg_578_pp0_iter13_reg;
                H_pred_0_addr_reg_578_pp0_iter15_reg <= H_pred_0_addr_reg_578_pp0_iter14_reg;
                H_pred_0_addr_reg_578_pp0_iter16_reg <= H_pred_0_addr_reg_578_pp0_iter15_reg;
                H_pred_0_addr_reg_578_pp0_iter17_reg <= H_pred_0_addr_reg_578_pp0_iter16_reg;
                H_pred_0_addr_reg_578_pp0_iter18_reg <= H_pred_0_addr_reg_578_pp0_iter17_reg;
                H_pred_1_addr_reg_583 <= zext_ln45_reg_461_pp0_iter11_reg(5 - 1 downto 0);
                H_pred_1_addr_reg_583_pp0_iter13_reg <= H_pred_1_addr_reg_583;
                H_pred_1_addr_reg_583_pp0_iter14_reg <= H_pred_1_addr_reg_583_pp0_iter13_reg;
                H_pred_1_addr_reg_583_pp0_iter15_reg <= H_pred_1_addr_reg_583_pp0_iter14_reg;
                H_pred_1_addr_reg_583_pp0_iter16_reg <= H_pred_1_addr_reg_583_pp0_iter15_reg;
                H_pred_1_addr_reg_583_pp0_iter17_reg <= H_pred_1_addr_reg_583_pp0_iter16_reg;
                H_pred_1_addr_reg_583_pp0_iter18_reg <= H_pred_1_addr_reg_583_pp0_iter17_reg;
                H_pred_2_addr_reg_588 <= zext_ln45_reg_461_pp0_iter11_reg(5 - 1 downto 0);
                H_pred_2_addr_reg_588_pp0_iter13_reg <= H_pred_2_addr_reg_588;
                H_pred_2_addr_reg_588_pp0_iter14_reg <= H_pred_2_addr_reg_588_pp0_iter13_reg;
                H_pred_2_addr_reg_588_pp0_iter15_reg <= H_pred_2_addr_reg_588_pp0_iter14_reg;
                H_pred_2_addr_reg_588_pp0_iter16_reg <= H_pred_2_addr_reg_588_pp0_iter15_reg;
                H_pred_2_addr_reg_588_pp0_iter17_reg <= H_pred_2_addr_reg_588_pp0_iter16_reg;
                H_pred_2_addr_reg_588_pp0_iter18_reg <= H_pred_2_addr_reg_588_pp0_iter17_reg;
                H_pred_3_addr_reg_573 <= zext_ln45_reg_461_pp0_iter11_reg(5 - 1 downto 0);
                H_pred_3_addr_reg_573_pp0_iter13_reg <= H_pred_3_addr_reg_573;
                H_pred_3_addr_reg_573_pp0_iter14_reg <= H_pred_3_addr_reg_573_pp0_iter13_reg;
                H_pred_3_addr_reg_573_pp0_iter15_reg <= H_pred_3_addr_reg_573_pp0_iter14_reg;
                H_pred_3_addr_reg_573_pp0_iter16_reg <= H_pred_3_addr_reg_573_pp0_iter15_reg;
                H_pred_3_addr_reg_573_pp0_iter17_reg <= H_pred_3_addr_reg_573_pp0_iter16_reg;
                H_pred_3_addr_reg_573_pp0_iter18_reg <= H_pred_3_addr_reg_573_pp0_iter17_reg;
                add1_reg_528 <= grp_fu_382_p_dout0;
                add53_1_reg_558 <= grp_fu_386_p_dout0;
                add53_2_reg_608 <= grp_fu_390_p_dout0;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                mul1_reg_503 <= grp_fu_398_p_dout0;
                mul48_1_reg_533 <= grp_fu_402_p_dout0;
                mul48_2_reg_563 <= grp_fu_406_p_dout0;
                mul48_3_reg_613 <= grp_fu_410_p_dout0;
                trunc_ln48_reg_484_pp0_iter10_reg <= trunc_ln48_reg_484_pp0_iter9_reg;
                trunc_ln48_reg_484_pp0_iter11_reg <= trunc_ln48_reg_484_pp0_iter10_reg;
                trunc_ln48_reg_484_pp0_iter12_reg <= trunc_ln48_reg_484_pp0_iter11_reg;
                trunc_ln48_reg_484_pp0_iter13_reg <= trunc_ln48_reg_484_pp0_iter12_reg;
                trunc_ln48_reg_484_pp0_iter14_reg <= trunc_ln48_reg_484_pp0_iter13_reg;
                trunc_ln48_reg_484_pp0_iter15_reg <= trunc_ln48_reg_484_pp0_iter14_reg;
                trunc_ln48_reg_484_pp0_iter16_reg <= trunc_ln48_reg_484_pp0_iter15_reg;
                trunc_ln48_reg_484_pp0_iter17_reg <= trunc_ln48_reg_484_pp0_iter16_reg;
                trunc_ln48_reg_484_pp0_iter18_reg <= trunc_ln48_reg_484_pp0_iter17_reg;
                trunc_ln48_reg_484_pp0_iter2_reg <= trunc_ln48_reg_484_pp0_iter1_reg;
                trunc_ln48_reg_484_pp0_iter3_reg <= trunc_ln48_reg_484_pp0_iter2_reg;
                trunc_ln48_reg_484_pp0_iter4_reg <= trunc_ln48_reg_484_pp0_iter3_reg;
                trunc_ln48_reg_484_pp0_iter5_reg <= trunc_ln48_reg_484_pp0_iter4_reg;
                trunc_ln48_reg_484_pp0_iter6_reg <= trunc_ln48_reg_484_pp0_iter5_reg;
                trunc_ln48_reg_484_pp0_iter7_reg <= trunc_ln48_reg_484_pp0_iter6_reg;
                trunc_ln48_reg_484_pp0_iter8_reg <= trunc_ln48_reg_484_pp0_iter7_reg;
                trunc_ln48_reg_484_pp0_iter9_reg <= trunc_ln48_reg_484_pp0_iter8_reg;
                    zext_ln45_reg_461_pp0_iter10_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter9_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter11_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter10_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter2_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter1_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter3_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter2_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter4_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter3_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter5_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter4_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter6_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter5_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter7_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter6_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter8_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter7_reg(5 downto 0);
                    zext_ln45_reg_461_pp0_iter9_reg(5 downto 0) <= zext_ln45_reg_461_pp0_iter8_reg(5 downto 0);
                    zext_ln48_reg_477_pp0_iter10_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter9_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter11_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter10_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter2_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter1_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter3_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter2_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter4_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter3_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter5_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter4_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter6_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter5_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter7_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter6_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter8_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter7_reg(2 downto 0);
                    zext_ln48_reg_477_pp0_iter9_reg(2 downto 0) <= zext_ln48_reg_477_pp0_iter8_reg(2 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln48_reg_484 <= trunc_ln48_fu_353_p1;
                trunc_ln48_reg_484_pp0_iter1_reg <= trunc_ln48_reg_484;
                    zext_ln45_reg_461(5 downto 0) <= zext_ln45_fu_343_p1(5 downto 0);
                    zext_ln45_reg_461_pp0_iter1_reg(5 downto 0) <= zext_ln45_reg_461(5 downto 0);
                    zext_ln48_reg_477(2 downto 0) <= zext_ln48_fu_348_p1(2 downto 0);
                    zext_ln48_reg_477_pp0_iter1_reg(2 downto 0) <= zext_ln48_reg_477(2 downto 0);
            end if;
        end if;
    end process;
    zext_ln45_reg_461(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter1_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter2_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter3_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter4_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter5_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter6_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter7_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter8_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter9_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter10_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln45_reg_461_pp0_iter11_reg(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter1_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter2_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter3_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter4_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter5_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter6_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter7_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter8_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter9_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter10_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    zext_ln48_reg_477_pp0_iter11_reg(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_0_address0 <= zext_ln48_fu_348_p1(2 - 1 downto 0);
    A_0_ce0 <= A_0_ce0_local;

    A_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            A_0_ce0_local <= ap_const_logic_1;
        else 
            A_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_1_address0 <= zext_ln48_reg_477_pp0_iter3_reg(2 - 1 downto 0);
    A_1_ce0 <= A_1_ce0_local;

    A_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            A_1_ce0_local <= ap_const_logic_1;
        else 
            A_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_2_address0 <= zext_ln48_reg_477_pp0_iter7_reg(2 - 1 downto 0);
    A_2_ce0 <= A_2_ce0_local;

    A_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            A_2_ce0_local <= ap_const_logic_1;
        else 
            A_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_3_address0 <= zext_ln48_reg_477_pp0_iter11_reg(2 - 1 downto 0);
    A_3_ce0 <= A_3_ce0_local;

    A_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            A_3_ce0_local <= ap_const_logic_1;
        else 
            A_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_0_address0 <= H_pred_0_addr_reg_578_pp0_iter18_reg;
    H_pred_0_ce0 <= H_pred_0_ce0_local;

    H_pred_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1))) then 
            H_pred_0_ce0_local <= ap_const_logic_1;
        else 
            H_pred_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_0_d0 <= bitcast_ln53_8_fu_428_p1;
    H_pred_0_we0 <= H_pred_0_we0_local;

    H_pred_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001, trunc_ln48_reg_484_pp0_iter18_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (trunc_ln48_reg_484_pp0_iter18_reg = ap_const_lv2_0))) then 
            H_pred_0_we0_local <= ap_const_logic_1;
        else 
            H_pred_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_1_address0 <= H_pred_1_addr_reg_583_pp0_iter18_reg;
    H_pred_1_ce0 <= H_pred_1_ce0_local;

    H_pred_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1))) then 
            H_pred_1_ce0_local <= ap_const_logic_1;
        else 
            H_pred_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_1_d0 <= bitcast_ln53_8_fu_428_p1;
    H_pred_1_we0 <= H_pred_1_we0_local;

    H_pred_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001, trunc_ln48_reg_484_pp0_iter18_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (trunc_ln48_reg_484_pp0_iter18_reg = ap_const_lv2_1))) then 
            H_pred_1_we0_local <= ap_const_logic_1;
        else 
            H_pred_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_2_address0 <= H_pred_2_addr_reg_588_pp0_iter18_reg;
    H_pred_2_ce0 <= H_pred_2_ce0_local;

    H_pred_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1))) then 
            H_pred_2_ce0_local <= ap_const_logic_1;
        else 
            H_pred_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_2_d0 <= bitcast_ln53_8_fu_428_p1;
    H_pred_2_we0 <= H_pred_2_we0_local;

    H_pred_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001, trunc_ln48_reg_484_pp0_iter18_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (trunc_ln48_reg_484_pp0_iter18_reg = ap_const_lv2_2))) then 
            H_pred_2_we0_local <= ap_const_logic_1;
        else 
            H_pred_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_3_address0 <= H_pred_3_addr_reg_573_pp0_iter18_reg;
    H_pred_3_ce0 <= H_pred_3_ce0_local;

    H_pred_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1))) then 
            H_pred_3_ce0_local <= ap_const_logic_1;
        else 
            H_pred_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_3_d0 <= bitcast_ln53_8_fu_428_p1;
    H_pred_3_we0 <= H_pred_3_we0_local;

    H_pred_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter19, ap_block_pp0_stage0_11001, trunc_ln48_reg_484_pp0_iter18_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1) and (trunc_ln48_reg_484_pp0_iter18_reg = ap_const_lv2_3))) then 
            H_pred_3_we0_local <= ap_const_logic_1;
        else 
            H_pred_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_x_0_address0 <= zext_ln45_fu_343_p1(5 - 1 downto 0);
    H_x_0_ce0 <= H_x_0_ce0_local;

    H_x_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_x_0_ce0_local <= ap_const_logic_1;
        else 
            H_x_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_x_1_address0 <= zext_ln45_reg_461_pp0_iter3_reg(5 - 1 downto 0);
    H_x_1_ce0 <= H_x_1_ce0_local;

    H_x_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            H_x_1_ce0_local <= ap_const_logic_1;
        else 
            H_x_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_x_2_address0 <= zext_ln45_reg_461_pp0_iter7_reg(5 - 1 downto 0);
    H_x_2_ce0 <= H_x_2_ce0_local;

    H_x_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            H_x_2_ce0_local <= ap_const_logic_1;
        else 
            H_x_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_x_3_address0 <= zext_ln45_reg_461_pp0_iter11_reg(5 - 1 downto 0);
    H_x_3_ce0 <= H_x_3_ce0_local;

    H_x_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            H_x_3_ce0_local <= ap_const_logic_1;
        else 
            H_x_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln45_1_fu_329_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_load) + unsigned(ap_const_lv6_1));
    add_ln45_fu_303_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv8_1));
    add_ln48_fu_367_p2 <= std_logic_vector(unsigned(select_ln32_fu_321_p3) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln45_fu_297_p2)
    begin
        if (((icmp_ln45_fu_297_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter18_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter18_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19)
    begin
        if (((ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_76, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_80)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_80;
        end if; 
    end process;

    bitcast_ln53_1_fu_398_p1 <= H_x_1_q0;
    bitcast_ln53_2_fu_408_p1 <= H_x_2_q0;
    bitcast_ln53_3_fu_418_p1 <= H_x_3_q0;
    bitcast_ln53_4_fu_393_p1 <= A_0_q0;
    bitcast_ln53_5_fu_403_p1 <= A_1_q0;
    bitcast_ln53_6_fu_413_p1 <= A_2_q0;
    bitcast_ln53_7_fu_423_p1 <= A_3_q0;
    bitcast_ln53_8_fu_428_p1 <= grp_fu_394_p_dout0;
    bitcast_ln53_fu_388_p1 <= H_x_0_q0;
    grp_fu_382_p_ce <= ap_const_logic_1;
    grp_fu_382_p_din0 <= mul1_reg_503;
    grp_fu_382_p_din1 <= ap_const_lv32_0;
    grp_fu_382_p_opcode <= ap_const_lv2_0;
    grp_fu_386_p_ce <= ap_const_logic_1;
    grp_fu_386_p_din0 <= add1_reg_528;
    grp_fu_386_p_din1 <= mul48_1_reg_533;
    grp_fu_386_p_opcode <= ap_const_lv2_0;
    grp_fu_390_p_ce <= ap_const_logic_1;
    grp_fu_390_p_din0 <= add53_1_reg_558;
    grp_fu_390_p_din1 <= mul48_2_reg_563;
    grp_fu_390_p_opcode <= ap_const_lv2_0;
    grp_fu_394_p_ce <= ap_const_logic_1;
    grp_fu_394_p_din0 <= add53_2_reg_608;
    grp_fu_394_p_din1 <= mul48_3_reg_613;
    grp_fu_394_p_opcode <= ap_const_lv2_0;
    grp_fu_398_p_ce <= ap_const_logic_1;
    grp_fu_398_p_din0 <= bitcast_ln53_4_fu_393_p1;
    grp_fu_398_p_din1 <= bitcast_ln53_fu_388_p1;
    grp_fu_402_p_ce <= ap_const_logic_1;
    grp_fu_402_p_din0 <= bitcast_ln53_5_fu_403_p1;
    grp_fu_402_p_din1 <= bitcast_ln53_1_fu_398_p1;
    grp_fu_406_p_ce <= ap_const_logic_1;
    grp_fu_406_p_din0 <= bitcast_ln53_6_fu_413_p1;
    grp_fu_406_p_din1 <= bitcast_ln53_2_fu_408_p1;
    grp_fu_410_p_ce <= ap_const_logic_1;
    grp_fu_410_p_din0 <= bitcast_ln53_7_fu_423_p1;
    grp_fu_410_p_din1 <= bitcast_ln53_3_fu_418_p1;
    icmp_ln45_fu_297_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = tmp_3) else "0";
    icmp_ln48_fu_315_p2 <= "1" when (ap_sig_allocacmp_i_load = ap_const_lv3_4) else "0";
    select_ln32_fu_321_p3 <= 
        ap_const_lv3_0 when (icmp_ln48_fu_315_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln45_fu_335_p3 <= 
        add_ln45_1_fu_329_p2 when (icmp_ln48_fu_315_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    trunc_ln48_fu_353_p1 <= select_ln32_fu_321_p3(2 - 1 downto 0);
    zext_ln45_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln45_fu_335_p3),64));
    zext_ln48_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln32_fu_321_p3),64));
end behav;
