[hls]
relative_roots=/home/zzh/minkowski_fpga/hls
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=predict_kernel/VITIS_LOOP_45_3  
syn.directive.loop_flatten=predict_kernel/VITIS_LOOP_59_6  


