// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_5,
        empty,
        H_w_0_address0,
        H_w_0_ce0,
        H_w_0_q0,
        H_w_1_address0,
        H_w_1_ce0,
        H_w_1_q0,
        H_w_2_address0,
        H_w_2_ce0,
        H_w_2_q0,
        H_w_3_address0,
        H_w_3_ce0,
        H_w_3_q0,
        H_pred_3_address0,
        H_pred_3_ce0,
        H_pred_3_we0,
        H_pred_3_d0,
        H_pred_0_address0,
        H_pred_0_ce0,
        H_pred_0_we0,
        H_pred_0_d0,
        H_pred_1_address0,
        H_pred_1_ce0,
        H_pred_1_we0,
        H_pred_1_d0,
        H_pred_2_address0,
        H_pred_2_ce0,
        H_pred_2_we0,
        H_pred_2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] tmp_5;
input  [4:0] empty;
output  [4:0] H_w_0_address0;
output   H_w_0_ce0;
input  [31:0] H_w_0_q0;
output  [4:0] H_w_1_address0;
output   H_w_1_ce0;
input  [31:0] H_w_1_q0;
output  [4:0] H_w_2_address0;
output   H_w_2_ce0;
input  [31:0] H_w_2_q0;
output  [4:0] H_w_3_address0;
output   H_w_3_ce0;
input  [31:0] H_w_3_q0;
output  [4:0] H_pred_3_address0;
output   H_pred_3_ce0;
output   H_pred_3_we0;
output  [31:0] H_pred_3_d0;
output  [4:0] H_pred_0_address0;
output   H_pred_0_ce0;
output   H_pred_0_we0;
output  [31:0] H_pred_0_d0;
output  [4:0] H_pred_1_address0;
output   H_pred_1_ce0;
output   H_pred_1_we0;
output  [31:0] H_pred_1_d0;
output  [4:0] H_pred_2_address0;
output   H_pred_2_ce0;
output   H_pred_2_we0;
output  [31:0] H_pred_2_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_222_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] add_ln63_fu_280_p2;
reg   [4:0] add_ln63_reg_399;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln61_fu_286_p1;
reg   [1:0] trunc_ln61_reg_424;
wire   [63:0] zext_ln59_fu_268_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln63_fu_321_p1;
reg   [2:0] i_fu_76;
wire   [2:0] add_ln61_fu_300_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_load;
reg   [5:0] k_fu_80;
wire   [5:0] select_ln59_fu_260_p3;
reg   [5:0] ap_sig_allocacmp_k_load;
reg   [7:0] indvar_flatten6_fu_84;
wire   [7:0] add_ln59_fu_228_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    H_w_0_ce0_local;
reg    H_w_1_ce0_local;
reg    H_w_2_ce0_local;
reg    H_w_3_ce0_local;
reg    H_pred_2_we0_local;
wire   [31:0] bitcast_ln63_4_fu_367_p1;
reg    H_pred_2_ce0_local;
reg    H_pred_1_we0_local;
reg    H_pred_1_ce0_local;
reg    H_pred_0_we0_local;
reg    H_pred_0_ce0_local;
reg    H_pred_3_we0_local;
reg    H_pred_3_ce0_local;
wire   [0:0] icmp_ln61_fu_240_p2;
wire   [5:0] add_ln59_1_fu_254_p2;
wire   [4:0] trunc_ln59_fu_276_p1;
wire   [2:0] select_ln32_fu_246_p3;
wire   [31:0] tmp_1_fu_344_p2;
wire   [31:0] tmp_1_fu_344_p4;
wire   [31:0] tmp_1_fu_344_p6;
wire   [31:0] tmp_1_fu_344_p8;
wire   [31:0] tmp_1_fu_344_p9;
wire   [31:0] tmp_1_fu_344_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_1_fu_344_p1;
wire   [1:0] tmp_1_fu_344_p3;
wire  signed [1:0] tmp_1_fu_344_p5;
wire  signed [1:0] tmp_1_fu_344_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_76 = 3'd0;
#0 k_fu_80 = 6'd0;
#0 indvar_flatten6_fu_84 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) predict_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U48(
    .din0(tmp_1_fu_344_p2),
    .din1(tmp_1_fu_344_p4),
    .din2(tmp_1_fu_344_p6),
    .din3(tmp_1_fu_344_p8),
    .def(tmp_1_fu_344_p9),
    .sel(trunc_ln61_reg_424),
    .dout(tmp_1_fu_344_p11)
);

predict_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_76 <= add_ln61_fu_300_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_84 <= add_ln59_fu_228_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_84 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_222_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            k_fu_80 <= select_ln59_fu_260_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_80 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln63_reg_399 <= add_ln63_fu_280_p2;
        trunc_ln61_reg_424 <= trunc_ln61_fu_286_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_pred_0_ce0_local = 1'b1;
    end else begin
        H_pred_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln61_reg_424 == 2'd0))) begin
        H_pred_0_we0_local = 1'b1;
    end else begin
        H_pred_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_pred_1_ce0_local = 1'b1;
    end else begin
        H_pred_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln61_reg_424 == 2'd1))) begin
        H_pred_1_we0_local = 1'b1;
    end else begin
        H_pred_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_pred_2_ce0_local = 1'b1;
    end else begin
        H_pred_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln61_reg_424 == 2'd2))) begin
        H_pred_2_we0_local = 1'b1;
    end else begin
        H_pred_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_pred_3_ce0_local = 1'b1;
    end else begin
        H_pred_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln61_reg_424 == 2'd3))) begin
        H_pred_3_we0_local = 1'b1;
    end else begin
        H_pred_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_w_0_ce0_local = 1'b1;
    end else begin
        H_w_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_w_1_ce0_local = 1'b1;
    end else begin
        H_w_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_w_2_ce0_local = 1'b1;
    end else begin
        H_w_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        H_w_3_ce0_local = 1'b1;
    end else begin
        H_w_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_222_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_load = 6'd0;
    end else begin
        ap_sig_allocacmp_k_load = k_fu_80;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_pred_0_address0 = zext_ln63_fu_321_p1;

assign H_pred_0_ce0 = H_pred_0_ce0_local;

assign H_pred_0_d0 = bitcast_ln63_4_fu_367_p1;

assign H_pred_0_we0 = H_pred_0_we0_local;

assign H_pred_1_address0 = zext_ln63_fu_321_p1;

assign H_pred_1_ce0 = H_pred_1_ce0_local;

assign H_pred_1_d0 = bitcast_ln63_4_fu_367_p1;

assign H_pred_1_we0 = H_pred_1_we0_local;

assign H_pred_2_address0 = zext_ln63_fu_321_p1;

assign H_pred_2_ce0 = H_pred_2_ce0_local;

assign H_pred_2_d0 = bitcast_ln63_4_fu_367_p1;

assign H_pred_2_we0 = H_pred_2_we0_local;

assign H_pred_3_address0 = zext_ln63_fu_321_p1;

assign H_pred_3_ce0 = H_pred_3_ce0_local;

assign H_pred_3_d0 = bitcast_ln63_4_fu_367_p1;

assign H_pred_3_we0 = H_pred_3_we0_local;

assign H_w_0_address0 = zext_ln59_fu_268_p1;

assign H_w_0_ce0 = H_w_0_ce0_local;

assign H_w_1_address0 = zext_ln59_fu_268_p1;

assign H_w_1_ce0 = H_w_1_ce0_local;

assign H_w_2_address0 = zext_ln59_fu_268_p1;

assign H_w_2_ce0 = H_w_2_ce0_local;

assign H_w_3_address0 = zext_ln59_fu_268_p1;

assign H_w_3_ce0 = H_w_3_ce0_local;

assign add_ln59_1_fu_254_p2 = (ap_sig_allocacmp_k_load + 6'd1);

assign add_ln59_fu_228_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 8'd1);

assign add_ln61_fu_300_p2 = (select_ln32_fu_246_p3 + 3'd1);

assign add_ln63_fu_280_p2 = (trunc_ln59_fu_276_p1 + empty);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln63_4_fu_367_p1 = tmp_1_fu_344_p11;

assign icmp_ln59_fu_222_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == tmp_5) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_240_p2 = ((ap_sig_allocacmp_i_load == 3'd4) ? 1'b1 : 1'b0);

assign select_ln32_fu_246_p3 = ((icmp_ln61_fu_240_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_i_load);

assign select_ln59_fu_260_p3 = ((icmp_ln61_fu_240_p2[0:0] == 1'b1) ? add_ln59_1_fu_254_p2 : ap_sig_allocacmp_k_load);

assign tmp_1_fu_344_p2 = H_w_0_q0;

assign tmp_1_fu_344_p4 = H_w_1_q0;

assign tmp_1_fu_344_p6 = H_w_2_q0;

assign tmp_1_fu_344_p8 = H_w_3_q0;

assign tmp_1_fu_344_p9 = 'bx;

assign trunc_ln59_fu_276_p1 = select_ln59_fu_260_p3[4:0];

assign trunc_ln61_fu_286_p1 = select_ln32_fu_246_p3[1:0];

assign zext_ln59_fu_268_p1 = select_ln59_fu_260_p3;

assign zext_ln63_fu_321_p1 = add_ln63_reg_399;

endmodule //predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7
