// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="predict_kernel_predict_kernel,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.016000,HLS_SYN_LAT=179,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3021,HLS_SYN_LUT=2850,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module predict_kernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_x_0,
        p_x_1,
        p_x_2,
        p_x_3,
        H_x_0_address0,
        H_x_0_ce0,
        H_x_0_q0,
        H_x_1_address0,
        H_x_1_ce0,
        H_x_1_q0,
        H_x_2_address0,
        H_x_2_ce0,
        H_x_2_q0,
        H_x_3_address0,
        H_x_3_ce0,
        H_x_3_q0,
        m_x,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        p_w_0,
        p_w_1,
        p_w_2,
        p_w_3,
        H_w_0_address0,
        H_w_0_ce0,
        H_w_0_q0,
        H_w_1_address0,
        H_w_1_ce0,
        H_w_1_q0,
        H_w_2_address0,
        H_w_2_ce0,
        H_w_2_q0,
        H_w_3_address0,
        H_w_3_ce0,
        H_w_3_q0,
        m_w,
        p_pred_0,
        p_pred_0_ap_vld,
        p_pred_1,
        p_pred_1_ap_vld,
        p_pred_2,
        p_pred_2_ap_vld,
        p_pred_3,
        p_pred_3_ap_vld,
        H_pred_0_address0,
        H_pred_0_ce0,
        H_pred_0_we0,
        H_pred_0_d0,
        H_pred_1_address0,
        H_pred_1_ce0,
        H_pred_1_we0,
        H_pred_1_d0,
        H_pred_2_address0,
        H_pred_2_ce0,
        H_pred_2_we0,
        H_pred_2_d0,
        H_pred_3_address0,
        H_pred_3_ce0,
        H_pred_3_we0,
        H_pred_3_d0,
        m_pred,
        m_pred_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_x_0;
input  [31:0] p_x_1;
input  [31:0] p_x_2;
input  [31:0] p_x_3;
output  [4:0] H_x_0_address0;
output   H_x_0_ce0;
input  [31:0] H_x_0_q0;
output  [4:0] H_x_1_address0;
output   H_x_1_ce0;
input  [31:0] H_x_1_q0;
output  [4:0] H_x_2_address0;
output   H_x_2_ce0;
input  [31:0] H_x_2_q0;
output  [4:0] H_x_3_address0;
output   H_x_3_ce0;
input  [31:0] H_x_3_q0;
input  [31:0] m_x;
output  [1:0] A_0_address0;
output   A_0_ce0;
input  [31:0] A_0_q0;
output  [1:0] A_1_address0;
output   A_1_ce0;
input  [31:0] A_1_q0;
output  [1:0] A_2_address0;
output   A_2_ce0;
input  [31:0] A_2_q0;
output  [1:0] A_3_address0;
output   A_3_ce0;
input  [31:0] A_3_q0;
input  [31:0] p_w_0;
input  [31:0] p_w_1;
input  [31:0] p_w_2;
input  [31:0] p_w_3;
output  [4:0] H_w_0_address0;
output   H_w_0_ce0;
input  [31:0] H_w_0_q0;
output  [4:0] H_w_1_address0;
output   H_w_1_ce0;
input  [31:0] H_w_1_q0;
output  [4:0] H_w_2_address0;
output   H_w_2_ce0;
input  [31:0] H_w_2_q0;
output  [4:0] H_w_3_address0;
output   H_w_3_ce0;
input  [31:0] H_w_3_q0;
input  [31:0] m_w;
output  [31:0] p_pred_0;
output   p_pred_0_ap_vld;
output  [31:0] p_pred_1;
output   p_pred_1_ap_vld;
output  [31:0] p_pred_2;
output   p_pred_2_ap_vld;
output  [31:0] p_pred_3;
output   p_pred_3_ap_vld;
output  [4:0] H_pred_0_address0;
output   H_pred_0_ce0;
output   H_pred_0_we0;
output  [31:0] H_pred_0_d0;
output  [4:0] H_pred_1_address0;
output   H_pred_1_ce0;
output   H_pred_1_we0;
output  [31:0] H_pred_1_d0;
output  [4:0] H_pred_2_address0;
output   H_pred_2_ce0;
output   H_pred_2_we0;
output  [31:0] H_pred_2_d0;
output  [4:0] H_pred_3_address0;
output   H_pred_3_ce0;
output   H_pred_3_we0;
output  [31:0] H_pred_3_d0;
output  [31:0] m_pred;
output   m_pred_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[1:0] A_0_address0;
reg A_0_ce0;
reg[1:0] A_1_address0;
reg A_1_ce0;
reg[1:0] A_2_address0;
reg A_2_ce0;
reg[1:0] A_3_address0;
reg A_3_ce0;
reg[31:0] p_pred_0;
reg[31:0] p_pred_1;
reg[31:0] p_pred_2;
reg[31:0] p_pred_3;
reg[4:0] H_pred_0_address0;
reg H_pred_0_ce0;
reg H_pred_0_we0;
reg[31:0] H_pred_0_d0;
reg[4:0] H_pred_1_address0;
reg H_pred_1_ce0;
reg H_pred_1_we0;
reg[31:0] H_pred_1_d0;
reg[4:0] H_pred_2_address0;
reg H_pred_2_ce0;
reg H_pred_2_we0;
reg[31:0] H_pred_2_d0;
reg[4:0] H_pred_3_address0;
reg H_pred_3_ce0;
reg H_pred_3_we0;
reg[31:0] H_pred_3_d0;
reg m_pred_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] bitcast_ln40_fu_242_p1;
reg   [31:0] bitcast_ln40_reg_322;
wire   [31:0] bitcast_ln40_1_fu_247_p1;
reg   [31:0] bitcast_ln40_1_reg_327;
wire   [31:0] bitcast_ln40_2_fu_252_p1;
reg   [31:0] bitcast_ln40_2_reg_332;
wire   [31:0] bitcast_ln40_3_fu_257_p1;
reg   [31:0] bitcast_ln40_3_reg_337;
wire   [31:0] bitcast_ln37_fu_262_p1;
reg   [31:0] bitcast_ln37_reg_342;
wire   [31:0] bitcast_ln37_1_fu_267_p1;
reg   [31:0] bitcast_ln37_1_reg_347;
wire   [31:0] bitcast_ln37_2_fu_272_p1;
reg   [31:0] bitcast_ln37_2_reg_352;
wire   [31:0] bitcast_ln37_3_fu_277_p1;
reg   [31:0] bitcast_ln37_3_reg_357;
wire   [5:0] trunc_ln8_fu_282_p1;
reg   [5:0] trunc_ln8_reg_362;
wire    ap_CS_fsm_state3;
wire   [4:0] trunc_ln45_fu_286_p1;
reg   [4:0] trunc_ln45_reg_367;
wire   [7:0] tmp_3_fu_290_p3;
reg   [7:0] tmp_3_reg_372;
wire   [7:0] tmp_5_fu_313_p3;
reg   [7:0] tmp_5_reg_377;
wire    ap_CS_fsm_state5;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_done;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_idle;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_ready;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0_ap_vld;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3_ap_vld;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2_ap_vld;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1_ap_vld;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_0_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_0_ce0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_1_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_1_ce0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_2_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_2_ce0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_3_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_3_ce0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_ce;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_done;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_idle;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_ready;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_0_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_0_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_1_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_1_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_2_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_2_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_3_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_3_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_d0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_d0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_d0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_d0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_0_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_0_ce0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_1_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_1_ce0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_2_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_2_ce0;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_3_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_3_ce0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_din1;
wire   [1:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_opcode;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_ce;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_din0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_din1;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_ce;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_done;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_idle;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_ready;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_0_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_0_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_1_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_1_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_2_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_2_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_3_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_3_ce0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_d0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_d0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_d0;
wire   [4:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_address0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_ce0;
wire    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_we0;
wire   [31:0] grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_d0;
reg    grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start_reg;
reg   [31:0] p_pred_0_reg;
wire    ap_CS_fsm_state2;
reg   [31:0] p_pred_3_reg;
reg   [31:0] p_pred_2_reg;
reg   [31:0] p_pred_1_reg;
reg    grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [5:0] trunc_ln8_1_fu_299_p1;
wire   [5:0] add_ln22_fu_303_p2;
wire   [31:0] grp_fu_382_p2;
reg   [31:0] grp_fu_382_p0;
reg   [31:0] grp_fu_382_p1;
reg    grp_fu_382_ce;
wire   [31:0] grp_fu_386_p2;
reg   [31:0] grp_fu_386_p0;
reg   [31:0] grp_fu_386_p1;
reg    grp_fu_386_ce;
wire   [31:0] grp_fu_390_p2;
reg   [31:0] grp_fu_390_p0;
reg   [31:0] grp_fu_390_p1;
reg    grp_fu_390_ce;
wire   [31:0] grp_fu_394_p2;
reg   [31:0] grp_fu_394_p0;
reg   [31:0] grp_fu_394_p1;
reg    grp_fu_394_ce;
wire   [31:0] grp_fu_398_p2;
reg   [31:0] grp_fu_398_p0;
reg   [31:0] grp_fu_398_p1;
reg    grp_fu_398_ce;
wire   [31:0] grp_fu_402_p2;
reg   [31:0] grp_fu_402_p0;
reg   [31:0] grp_fu_402_p1;
reg    grp_fu_402_ce;
wire   [31:0] grp_fu_406_p2;
reg   [31:0] grp_fu_406_p0;
reg   [31:0] grp_fu_406_p1;
reg    grp_fu_406_ce;
wire   [31:0] grp_fu_410_p2;
reg   [31:0] grp_fu_410_p0;
reg   [31:0] grp_fu_410_p1;
reg    grp_fu_410_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start_reg = 1'b0;
#0 grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start_reg = 1'b0;
#0 grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start_reg = 1'b0;
end

predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_35_1 grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start),
    .ap_done(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_done),
    .ap_idle(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_idle),
    .ap_ready(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_ready),
    .p_pred_0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0),
    .p_pred_0_ap_vld(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0_ap_vld),
    .p_pred_3(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3),
    .p_pred_3_ap_vld(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3_ap_vld),
    .p_pred_2(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2),
    .p_pred_2_ap_vld(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2_ap_vld),
    .p_pred_1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1),
    .p_pred_1_ap_vld(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1_ap_vld),
    .bitcast_ln37(bitcast_ln37_reg_342),
    .bitcast_ln37_1(bitcast_ln37_1_reg_347),
    .bitcast_ln37_2(bitcast_ln37_2_reg_352),
    .bitcast_ln37_3(bitcast_ln37_3_reg_357),
    .A_0_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_0_address0),
    .A_0_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_0_ce0),
    .A_0_q0(A_0_q0),
    .bitcast_ln40(bitcast_ln40_reg_322),
    .A_1_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_1_address0),
    .A_1_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_1_ce0),
    .A_1_q0(A_1_q0),
    .bitcast_ln40_1(bitcast_ln40_1_reg_327),
    .A_2_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_2_address0),
    .A_2_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_2_ce0),
    .A_2_q0(A_2_q0),
    .bitcast_ln40_2(bitcast_ln40_2_reg_332),
    .A_3_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_3_address0),
    .A_3_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_3_ce0),
    .A_3_q0(A_3_q0),
    .bitcast_ln40_3(bitcast_ln40_3_reg_337),
    .grp_fu_382_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_din0),
    .grp_fu_382_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_din1),
    .grp_fu_382_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_opcode),
    .grp_fu_382_p_dout0(grp_fu_382_p2),
    .grp_fu_382_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_ce),
    .grp_fu_386_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_din0),
    .grp_fu_386_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_din1),
    .grp_fu_386_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_opcode),
    .grp_fu_386_p_dout0(grp_fu_386_p2),
    .grp_fu_386_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_ce),
    .grp_fu_390_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_din0),
    .grp_fu_390_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_din1),
    .grp_fu_390_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_opcode),
    .grp_fu_390_p_dout0(grp_fu_390_p2),
    .grp_fu_390_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_ce),
    .grp_fu_394_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_din0),
    .grp_fu_394_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_din1),
    .grp_fu_394_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_opcode),
    .grp_fu_394_p_dout0(grp_fu_394_p2),
    .grp_fu_394_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_ce),
    .grp_fu_398_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_din0),
    .grp_fu_398_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_din1),
    .grp_fu_398_p_dout0(grp_fu_398_p2),
    .grp_fu_398_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_ce),
    .grp_fu_402_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_din0),
    .grp_fu_402_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_din1),
    .grp_fu_402_p_dout0(grp_fu_402_p2),
    .grp_fu_402_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_ce),
    .grp_fu_406_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_din0),
    .grp_fu_406_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_din1),
    .grp_fu_406_p_dout0(grp_fu_406_p2),
    .grp_fu_406_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_ce),
    .grp_fu_410_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_din0),
    .grp_fu_410_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_din1),
    .grp_fu_410_p_dout0(grp_fu_410_p2),
    .grp_fu_410_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_ce)
);

predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4 grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start),
    .ap_done(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_done),
    .ap_idle(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_idle),
    .ap_ready(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_ready),
    .tmp_3(tmp_3_reg_372),
    .H_x_0_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_0_address0),
    .H_x_0_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_0_ce0),
    .H_x_0_q0(H_x_0_q0),
    .H_x_1_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_1_address0),
    .H_x_1_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_1_ce0),
    .H_x_1_q0(H_x_1_q0),
    .H_x_2_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_2_address0),
    .H_x_2_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_2_ce0),
    .H_x_2_q0(H_x_2_q0),
    .H_x_3_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_3_address0),
    .H_x_3_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_3_ce0),
    .H_x_3_q0(H_x_3_q0),
    .H_pred_3_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_address0),
    .H_pred_3_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_ce0),
    .H_pred_3_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_we0),
    .H_pred_3_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_d0),
    .H_pred_0_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_address0),
    .H_pred_0_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_ce0),
    .H_pred_0_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_we0),
    .H_pred_0_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_d0),
    .H_pred_1_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_address0),
    .H_pred_1_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_ce0),
    .H_pred_1_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_we0),
    .H_pred_1_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_d0),
    .H_pred_2_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_address0),
    .H_pred_2_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_ce0),
    .H_pred_2_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_we0),
    .H_pred_2_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_d0),
    .A_0_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_0_address0),
    .A_0_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_0_ce0),
    .A_0_q0(A_0_q0),
    .A_1_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_1_address0),
    .A_1_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_2_address0),
    .A_2_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_3_address0),
    .A_3_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_3_ce0),
    .A_3_q0(A_3_q0),
    .grp_fu_382_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_din0),
    .grp_fu_382_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_din1),
    .grp_fu_382_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_opcode),
    .grp_fu_382_p_dout0(grp_fu_382_p2),
    .grp_fu_382_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_ce),
    .grp_fu_386_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_din0),
    .grp_fu_386_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_din1),
    .grp_fu_386_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_opcode),
    .grp_fu_386_p_dout0(grp_fu_386_p2),
    .grp_fu_386_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_ce),
    .grp_fu_390_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_din0),
    .grp_fu_390_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_din1),
    .grp_fu_390_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_opcode),
    .grp_fu_390_p_dout0(grp_fu_390_p2),
    .grp_fu_390_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_ce),
    .grp_fu_394_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_din0),
    .grp_fu_394_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_din1),
    .grp_fu_394_p_opcode(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_opcode),
    .grp_fu_394_p_dout0(grp_fu_394_p2),
    .grp_fu_394_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_ce),
    .grp_fu_398_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_din0),
    .grp_fu_398_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_din1),
    .grp_fu_398_p_dout0(grp_fu_398_p2),
    .grp_fu_398_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_ce),
    .grp_fu_402_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_din0),
    .grp_fu_402_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_din1),
    .grp_fu_402_p_dout0(grp_fu_402_p2),
    .grp_fu_402_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_ce),
    .grp_fu_406_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_din0),
    .grp_fu_406_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_din1),
    .grp_fu_406_p_dout0(grp_fu_406_p2),
    .grp_fu_406_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_ce),
    .grp_fu_410_p_din0(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_din0),
    .grp_fu_410_p_din1(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_din1),
    .grp_fu_410_p_dout0(grp_fu_410_p2),
    .grp_fu_410_p_ce(grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_ce)
);

predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7 grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start),
    .ap_done(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_done),
    .ap_idle(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_idle),
    .ap_ready(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_ready),
    .tmp_5(tmp_5_reg_377),
    .empty(trunc_ln45_reg_367),
    .H_w_0_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_0_address0),
    .H_w_0_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_0_ce0),
    .H_w_0_q0(H_w_0_q0),
    .H_w_1_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_1_address0),
    .H_w_1_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_1_ce0),
    .H_w_1_q0(H_w_1_q0),
    .H_w_2_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_2_address0),
    .H_w_2_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_2_ce0),
    .H_w_2_q0(H_w_2_q0),
    .H_w_3_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_3_address0),
    .H_w_3_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_3_ce0),
    .H_w_3_q0(H_w_3_q0),
    .H_pred_3_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_address0),
    .H_pred_3_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_ce0),
    .H_pred_3_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_we0),
    .H_pred_3_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_d0),
    .H_pred_0_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_address0),
    .H_pred_0_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_ce0),
    .H_pred_0_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_we0),
    .H_pred_0_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_d0),
    .H_pred_1_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_address0),
    .H_pred_1_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_ce0),
    .H_pred_1_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_we0),
    .H_pred_1_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_d0),
    .H_pred_2_address0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_address0),
    .H_pred_2_ce0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_ce0),
    .H_pred_2_we0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_we0),
    .H_pred_2_d0(grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_d0)
);

predict_kernel_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_382_p0),
    .din1(grp_fu_382_p1),
    .ce(grp_fu_382_ce),
    .dout(grp_fu_382_p2)
);

predict_kernel_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_386_p0),
    .din1(grp_fu_386_p1),
    .ce(grp_fu_386_ce),
    .dout(grp_fu_386_p2)
);

predict_kernel_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_390_p0),
    .din1(grp_fu_390_p1),
    .ce(grp_fu_390_ce),
    .dout(grp_fu_390_p2)
);

predict_kernel_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_394_p0),
    .din1(grp_fu_394_p1),
    .ce(grp_fu_394_ce),
    .dout(grp_fu_394_p2)
);

predict_kernel_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_398_p0),
    .din1(grp_fu_398_p1),
    .ce(grp_fu_398_ce),
    .dout(grp_fu_398_p2)
);

predict_kernel_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_402_p0),
    .din1(grp_fu_402_p1),
    .ce(grp_fu_402_ce),
    .dout(grp_fu_402_p2)
);

predict_kernel_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_406_p0),
    .din1(grp_fu_406_p1),
    .ce(grp_fu_406_ce),
    .dout(grp_fu_406_p2)
);

predict_kernel_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_410_p0),
    .din1(grp_fu_410_p1),
    .ce(grp_fu_410_ce),
    .dout(grp_fu_410_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start_reg <= 1'b1;
        end else if ((grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_ready == 1'b1)) begin
            grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start_reg <= 1'b1;
        end else if ((grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_ready == 1'b1)) begin
            grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start_reg <= 1'b1;
        end else if ((grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_ready == 1'b1)) begin
            grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bitcast_ln37_1_reg_347 <= bitcast_ln37_1_fu_267_p1;
        bitcast_ln37_2_reg_352 <= bitcast_ln37_2_fu_272_p1;
        bitcast_ln37_3_reg_357 <= bitcast_ln37_3_fu_277_p1;
        bitcast_ln37_reg_342 <= bitcast_ln37_fu_262_p1;
        bitcast_ln40_1_reg_327 <= bitcast_ln40_1_fu_247_p1;
        bitcast_ln40_2_reg_332 <= bitcast_ln40_2_fu_252_p1;
        bitcast_ln40_3_reg_337 <= bitcast_ln40_3_fu_257_p1;
        bitcast_ln40_reg_322 <= bitcast_ln40_fu_242_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0_ap_vld == 1'b1))) begin
        p_pred_0_reg <= grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1_ap_vld == 1'b1))) begin
        p_pred_1_reg <= grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2_ap_vld == 1'b1))) begin
        p_pred_2_reg <= grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3_ap_vld == 1'b1))) begin
        p_pred_3_reg <= grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_3_reg_372[7 : 2] <= tmp_3_fu_290_p3[7 : 2];
        trunc_ln45_reg_367 <= trunc_ln45_fu_286_p1;
        trunc_ln8_reg_362 <= trunc_ln8_fu_282_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_5_reg_377[7 : 2] <= tmp_5_fu_313_p3[7 : 2];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_0_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_0_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_0_address0;
    end else begin
        A_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_0_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_0_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_0_ce0;
    end else begin
        A_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_1_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_1_address0;
    end else begin
        A_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_1_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_1_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_1_ce0;
    end else begin
        A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_2_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_2_address0;
    end else begin
        A_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_2_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_2_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_2_ce0;
    end else begin
        A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_3_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_3_address0;
    end else begin
        A_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_3_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_3_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_A_3_ce0;
    end else begin
        A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_0_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_0_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_address0;
    end else begin
        H_pred_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_0_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_0_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_ce0;
    end else begin
        H_pred_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_0_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_0_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_d0;
    end else begin
        H_pred_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_0_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_0_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_0_we0;
    end else begin
        H_pred_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_1_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_1_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_address0;
    end else begin
        H_pred_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_1_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_1_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_ce0;
    end else begin
        H_pred_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_1_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_1_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_d0;
    end else begin
        H_pred_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_1_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_1_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_1_we0;
    end else begin
        H_pred_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_2_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_2_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_address0;
    end else begin
        H_pred_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_2_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_2_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_ce0;
    end else begin
        H_pred_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_2_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_2_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_d0;
    end else begin
        H_pred_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_2_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_2_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_2_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_2_we0;
    end else begin
        H_pred_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_3_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_3_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_address0;
    end else begin
        H_pred_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_3_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_3_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_ce0;
    end else begin
        H_pred_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_3_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_3_d0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_d0;
    end else begin
        H_pred_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        H_pred_3_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_pred_3_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        H_pred_3_we0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_pred_3_we0;
    end else begin
        H_pred_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_382_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_382_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_ce;
    end else begin
        grp_fu_382_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_382_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_382_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_din0;
    end else begin
        grp_fu_382_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_382_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_382_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_382_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_382_p_din1;
    end else begin
        grp_fu_382_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_386_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_386_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_ce;
    end else begin
        grp_fu_386_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_386_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_386_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_din0;
    end else begin
        grp_fu_386_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_386_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_386_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_386_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_386_p_din1;
    end else begin
        grp_fu_386_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_390_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_390_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_ce;
    end else begin
        grp_fu_390_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_390_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_390_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_din0;
    end else begin
        grp_fu_390_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_390_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_390_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_390_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_390_p_din1;
    end else begin
        grp_fu_390_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_394_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_394_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_ce;
    end else begin
        grp_fu_394_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_394_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_394_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_din0;
    end else begin
        grp_fu_394_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_394_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_394_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_394_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_394_p_din1;
    end else begin
        grp_fu_394_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_398_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_398_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_ce;
    end else begin
        grp_fu_398_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_398_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_398_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_din0;
    end else begin
        grp_fu_398_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_398_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_398_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_398_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_398_p_din1;
    end else begin
        grp_fu_398_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_402_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_402_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_ce;
    end else begin
        grp_fu_402_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_402_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_402_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_din0;
    end else begin
        grp_fu_402_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_402_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_402_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_402_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_402_p_din1;
    end else begin
        grp_fu_402_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_406_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_406_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_ce;
    end else begin
        grp_fu_406_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_406_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_406_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_din0;
    end else begin
        grp_fu_406_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_406_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_406_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_406_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_406_p_din1;
    end else begin
        grp_fu_406_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_410_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_410_ce = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_ce;
    end else begin
        grp_fu_410_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_410_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_410_p0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_din0;
    end else begin
        grp_fu_410_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_410_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_grp_fu_410_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_410_p1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_grp_fu_410_p_din1;
    end else begin
        grp_fu_410_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        m_pred_ap_vld = 1'b1;
    end else begin
        m_pred_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0_ap_vld == 1'b1))) begin
        p_pred_0 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0;
    end else begin
        p_pred_0 = p_pred_0_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1_ap_vld == 1'b1))) begin
        p_pred_1 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1;
    end else begin
        p_pred_1 = p_pred_1_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2_ap_vld == 1'b1))) begin
        p_pred_2 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2;
    end else begin
        p_pred_2 = p_pred_2_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3_ap_vld == 1'b1))) begin
        p_pred_3 = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3;
    end else begin
        p_pred_3 = p_pred_3_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign H_w_0_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_0_address0;

assign H_w_0_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_0_ce0;

assign H_w_1_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_1_address0;

assign H_w_1_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_1_ce0;

assign H_w_2_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_2_address0;

assign H_w_2_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_2_ce0;

assign H_w_3_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_3_address0;

assign H_w_3_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_H_w_3_ce0;

assign H_x_0_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_0_address0;

assign H_x_0_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_0_ce0;

assign H_x_1_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_1_address0;

assign H_x_1_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_1_ce0;

assign H_x_2_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_2_address0;

assign H_x_2_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_2_ce0;

assign H_x_3_address0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_3_address0;

assign H_x_3_ce0 = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_H_x_3_ce0;

assign add_ln22_fu_303_p2 = (trunc_ln8_1_fu_299_p1 + trunc_ln8_reg_362);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign bitcast_ln37_1_fu_267_p1 = p_w_1;

assign bitcast_ln37_2_fu_272_p1 = p_w_2;

assign bitcast_ln37_3_fu_277_p1 = p_w_3;

assign bitcast_ln37_fu_262_p1 = p_w_0;

assign bitcast_ln40_1_fu_247_p1 = p_x_1;

assign bitcast_ln40_2_fu_252_p1 = p_x_2;

assign bitcast_ln40_3_fu_257_p1 = p_x_3;

assign bitcast_ln40_fu_242_p1 = p_x_0;

assign grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_ap_start_reg;

assign grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start = grp_predict_kernel_Pipeline_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_191_ap_start_reg;

assign grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start = grp_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7_fu_220_ap_start_reg;

assign m_pred = add_ln22_fu_303_p2;

assign p_pred_0_ap_vld = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_0_ap_vld;

assign p_pred_1_ap_vld = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_1_ap_vld;

assign p_pred_2_ap_vld = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_2_ap_vld;

assign p_pred_3_ap_vld = grp_predict_kernel_Pipeline_VITIS_LOOP_35_1_fu_163_p_pred_3_ap_vld;

assign tmp_3_fu_290_p3 = {{trunc_ln8_fu_282_p1}, {2'd0}};

assign tmp_5_fu_313_p3 = {{trunc_ln8_1_fu_299_p1}, {2'd0}};

assign trunc_ln45_fu_286_p1 = m_x[4:0];

assign trunc_ln8_1_fu_299_p1 = m_w[5:0];

assign trunc_ln8_fu_282_p1 = m_x[5:0];

always @ (posedge ap_clk) begin
    tmp_3_reg_372[1:0] <= 2'b00;
    tmp_5_reg_377[1:0] <= 2'b00;
end

endmodule //predict_kernel
