-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    tmp_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    empty : IN STD_LOGIC_VECTOR (4 downto 0);
    H_w_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_w_0_ce0 : OUT STD_LOGIC;
    H_w_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_w_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_w_1_ce0 : OUT STD_LOGIC;
    H_w_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_w_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_w_2_ce0 : OUT STD_LOGIC;
    H_w_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_w_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_w_3_ce0 : OUT STD_LOGIC;
    H_w_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    H_pred_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_3_ce0 : OUT STD_LOGIC;
    H_pred_3_we0 : OUT STD_LOGIC;
    H_pred_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    H_pred_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_0_ce0 : OUT STD_LOGIC;
    H_pred_0_we0 : OUT STD_LOGIC;
    H_pred_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    H_pred_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_1_ce0 : OUT STD_LOGIC;
    H_pred_1_we0 : OUT STD_LOGIC;
    H_pred_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    H_pred_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    H_pred_2_ce0 : OUT STD_LOGIC;
    H_pred_2_we0 : OUT STD_LOGIC;
    H_pred_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_59_6_VITIS_LOOP_61_7 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln59_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal add_ln63_fu_280_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln63_reg_399 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln61_fu_286_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln61_reg_424 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln59_fu_268_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln63_fu_321_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln61_fu_300_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal k_fu_80 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln59_fu_260_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_k_load : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten6_fu_84 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln59_fu_228_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (7 downto 0);
    signal H_w_0_ce0_local : STD_LOGIC;
    signal H_w_1_ce0_local : STD_LOGIC;
    signal H_w_2_ce0_local : STD_LOGIC;
    signal H_w_3_ce0_local : STD_LOGIC;
    signal H_pred_2_we0_local : STD_LOGIC;
    signal bitcast_ln63_4_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_pred_2_ce0_local : STD_LOGIC;
    signal H_pred_1_we0_local : STD_LOGIC;
    signal H_pred_1_ce0_local : STD_LOGIC;
    signal H_pred_0_we0_local : STD_LOGIC;
    signal H_pred_0_ce0_local : STD_LOGIC;
    signal H_pred_3_we0_local : STD_LOGIC;
    signal H_pred_3_ce0_local : STD_LOGIC;
    signal icmp_ln61_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_1_fu_254_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln59_fu_276_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln32_fu_246_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_344_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_344_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_344_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_344_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_344_p9 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_344_p11 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_1_fu_344_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_344_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_344_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_344_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component predict_kernel_sparsemux_9_2_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component predict_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_32_1_1_U48 : component predict_kernel_sparsemux_9_2_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 32,
        CASE1 => "01",
        din1_WIDTH => 32,
        CASE2 => "10",
        din2_WIDTH => 32,
        CASE3 => "11",
        din3_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => tmp_1_fu_344_p2,
        din1 => tmp_1_fu_344_p4,
        din2 => tmp_1_fu_344_p6,
        din3 => tmp_1_fu_344_p8,
        def => tmp_1_fu_344_p9,
        sel => trunc_ln61_reg_424,
        dout => tmp_1_fu_344_p11);

    flow_control_loop_pipe_sequential_init_U : component predict_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln59_fu_222_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_76 <= add_ln61_fu_300_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_76 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln59_fu_222_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_84 <= add_ln59_fu_228_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_84 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln59_fu_222_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_80 <= select_ln59_fu_260_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_80 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln63_reg_399 <= add_ln63_fu_280_p2;
                trunc_ln61_reg_424 <= trunc_ln61_fu_286_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    H_pred_0_address0 <= zext_ln63_fu_321_p1(5 - 1 downto 0);
    H_pred_0_ce0 <= H_pred_0_ce0_local;

    H_pred_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_pred_0_ce0_local <= ap_const_logic_1;
        else 
            H_pred_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_0_d0 <= bitcast_ln63_4_fu_367_p1;
    H_pred_0_we0 <= H_pred_0_we0_local;

    H_pred_0_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln61_reg_424)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln61_reg_424 = ap_const_lv2_0))) then 
            H_pred_0_we0_local <= ap_const_logic_1;
        else 
            H_pred_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_1_address0 <= zext_ln63_fu_321_p1(5 - 1 downto 0);
    H_pred_1_ce0 <= H_pred_1_ce0_local;

    H_pred_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_pred_1_ce0_local <= ap_const_logic_1;
        else 
            H_pred_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_1_d0 <= bitcast_ln63_4_fu_367_p1;
    H_pred_1_we0 <= H_pred_1_we0_local;

    H_pred_1_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln61_reg_424)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln61_reg_424 = ap_const_lv2_1))) then 
            H_pred_1_we0_local <= ap_const_logic_1;
        else 
            H_pred_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_2_address0 <= zext_ln63_fu_321_p1(5 - 1 downto 0);
    H_pred_2_ce0 <= H_pred_2_ce0_local;

    H_pred_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_pred_2_ce0_local <= ap_const_logic_1;
        else 
            H_pred_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_2_d0 <= bitcast_ln63_4_fu_367_p1;
    H_pred_2_we0 <= H_pred_2_we0_local;

    H_pred_2_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln61_reg_424)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln61_reg_424 = ap_const_lv2_2))) then 
            H_pred_2_we0_local <= ap_const_logic_1;
        else 
            H_pred_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_3_address0 <= zext_ln63_fu_321_p1(5 - 1 downto 0);
    H_pred_3_ce0 <= H_pred_3_ce0_local;

    H_pred_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_pred_3_ce0_local <= ap_const_logic_1;
        else 
            H_pred_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_pred_3_d0 <= bitcast_ln63_4_fu_367_p1;
    H_pred_3_we0 <= H_pred_3_we0_local;

    H_pred_3_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln61_reg_424)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln61_reg_424 = ap_const_lv2_3))) then 
            H_pred_3_we0_local <= ap_const_logic_1;
        else 
            H_pred_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_w_0_address0 <= zext_ln59_fu_268_p1(5 - 1 downto 0);
    H_w_0_ce0 <= H_w_0_ce0_local;

    H_w_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_w_0_ce0_local <= ap_const_logic_1;
        else 
            H_w_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_w_1_address0 <= zext_ln59_fu_268_p1(5 - 1 downto 0);
    H_w_1_ce0 <= H_w_1_ce0_local;

    H_w_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_w_1_ce0_local <= ap_const_logic_1;
        else 
            H_w_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_w_2_address0 <= zext_ln59_fu_268_p1(5 - 1 downto 0);
    H_w_2_ce0 <= H_w_2_ce0_local;

    H_w_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_w_2_ce0_local <= ap_const_logic_1;
        else 
            H_w_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    H_w_3_address0 <= zext_ln59_fu_268_p1(5 - 1 downto 0);
    H_w_3_ce0 <= H_w_3_ce0_local;

    H_w_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            H_w_3_ce0_local <= ap_const_logic_1;
        else 
            H_w_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln59_1_fu_254_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_load) + unsigned(ap_const_lv6_1));
    add_ln59_fu_228_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv8_1));
    add_ln61_fu_300_p2 <= std_logic_vector(unsigned(select_ln32_fu_246_p3) + unsigned(ap_const_lv3_1));
    add_ln63_fu_280_p2 <= std_logic_vector(unsigned(trunc_ln59_fu_276_p1) + unsigned(empty));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln59_fu_222_p2)
    begin
        if (((icmp_ln59_fu_222_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_76, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_k_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_80)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_k_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_k_load <= k_fu_80;
        end if; 
    end process;

    bitcast_ln63_4_fu_367_p1 <= tmp_1_fu_344_p11;
    icmp_ln59_fu_222_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = tmp_5) else "0";
    icmp_ln61_fu_240_p2 <= "1" when (ap_sig_allocacmp_i_load = ap_const_lv3_4) else "0";
    select_ln32_fu_246_p3 <= 
        ap_const_lv3_0 when (icmp_ln61_fu_240_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln59_fu_260_p3 <= 
        add_ln59_1_fu_254_p2 when (icmp_ln61_fu_240_p2(0) = '1') else 
        ap_sig_allocacmp_k_load;
    tmp_1_fu_344_p2 <= H_w_0_q0;
    tmp_1_fu_344_p4 <= H_w_1_q0;
    tmp_1_fu_344_p6 <= H_w_2_q0;
    tmp_1_fu_344_p8 <= H_w_3_q0;
    tmp_1_fu_344_p9 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln59_fu_276_p1 <= select_ln59_fu_260_p3(5 - 1 downto 0);
    trunc_ln61_fu_286_p1 <= select_ln32_fu_246_p3(2 - 1 downto 0);
    zext_ln59_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln59_fu_260_p3),64));
    zext_ln63_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln63_reg_399),64));
end behav;
