// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_35_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_pred_0,
        p_pred_0_ap_vld,
        p_pred_3,
        p_pred_3_ap_vld,
        p_pred_2,
        p_pred_2_ap_vld,
        p_pred_1,
        p_pred_1_ap_vld,
        bitcast_ln37,
        bitcast_ln37_1,
        bitcast_ln37_2,
        bitcast_ln37_3,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        bitcast_ln40,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        bitcast_ln40_1,
        A_2_address0,
        A_2_ce0,
        A_2_q0,
        bitcast_ln40_2,
        A_3_address0,
        A_3_ce0,
        A_3_q0,
        bitcast_ln40_3,
        grp_fu_382_p_din0,
        grp_fu_382_p_din1,
        grp_fu_382_p_opcode,
        grp_fu_382_p_dout0,
        grp_fu_382_p_ce,
        grp_fu_386_p_din0,
        grp_fu_386_p_din1,
        grp_fu_386_p_opcode,
        grp_fu_386_p_dout0,
        grp_fu_386_p_ce,
        grp_fu_390_p_din0,
        grp_fu_390_p_din1,
        grp_fu_390_p_opcode,
        grp_fu_390_p_dout0,
        grp_fu_390_p_ce,
        grp_fu_394_p_din0,
        grp_fu_394_p_din1,
        grp_fu_394_p_opcode,
        grp_fu_394_p_dout0,
        grp_fu_394_p_ce,
        grp_fu_398_p_din0,
        grp_fu_398_p_din1,
        grp_fu_398_p_dout0,
        grp_fu_398_p_ce,
        grp_fu_402_p_din0,
        grp_fu_402_p_din1,
        grp_fu_402_p_dout0,
        grp_fu_402_p_ce,
        grp_fu_406_p_din0,
        grp_fu_406_p_din1,
        grp_fu_406_p_dout0,
        grp_fu_406_p_ce,
        grp_fu_410_p_din0,
        grp_fu_410_p_din1,
        grp_fu_410_p_dout0,
        grp_fu_410_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] p_pred_0;
output   p_pred_0_ap_vld;
output  [31:0] p_pred_3;
output   p_pred_3_ap_vld;
output  [31:0] p_pred_2;
output   p_pred_2_ap_vld;
output  [31:0] p_pred_1;
output   p_pred_1_ap_vld;
input  [31:0] bitcast_ln37;
input  [31:0] bitcast_ln37_1;
input  [31:0] bitcast_ln37_2;
input  [31:0] bitcast_ln37_3;
output  [1:0] A_0_address0;
output   A_0_ce0;
input  [31:0] A_0_q0;
input  [31:0] bitcast_ln40;
output  [1:0] A_1_address0;
output   A_1_ce0;
input  [31:0] A_1_q0;
input  [31:0] bitcast_ln40_1;
output  [1:0] A_2_address0;
output   A_2_ce0;
input  [31:0] A_2_q0;
input  [31:0] bitcast_ln40_2;
output  [1:0] A_3_address0;
output   A_3_ce0;
input  [31:0] A_3_q0;
input  [31:0] bitcast_ln40_3;
output  [31:0] grp_fu_382_p_din0;
output  [31:0] grp_fu_382_p_din1;
output  [1:0] grp_fu_382_p_opcode;
input  [31:0] grp_fu_382_p_dout0;
output   grp_fu_382_p_ce;
output  [31:0] grp_fu_386_p_din0;
output  [31:0] grp_fu_386_p_din1;
output  [1:0] grp_fu_386_p_opcode;
input  [31:0] grp_fu_386_p_dout0;
output   grp_fu_386_p_ce;
output  [31:0] grp_fu_390_p_din0;
output  [31:0] grp_fu_390_p_din1;
output  [1:0] grp_fu_390_p_opcode;
input  [31:0] grp_fu_390_p_dout0;
output   grp_fu_390_p_ce;
output  [31:0] grp_fu_394_p_din0;
output  [31:0] grp_fu_394_p_din1;
output  [1:0] grp_fu_394_p_opcode;
input  [31:0] grp_fu_394_p_dout0;
output   grp_fu_394_p_ce;
output  [31:0] grp_fu_398_p_din0;
output  [31:0] grp_fu_398_p_din1;
input  [31:0] grp_fu_398_p_dout0;
output   grp_fu_398_p_ce;
output  [31:0] grp_fu_402_p_din0;
output  [31:0] grp_fu_402_p_din1;
input  [31:0] grp_fu_402_p_dout0;
output   grp_fu_402_p_ce;
output  [31:0] grp_fu_406_p_din0;
output  [31:0] grp_fu_406_p_din1;
input  [31:0] grp_fu_406_p_dout0;
output   grp_fu_406_p_ce;
output  [31:0] grp_fu_410_p_din0;
output  [31:0] grp_fu_410_p_din1;
input  [31:0] grp_fu_410_p_dout0;
output   grp_fu_410_p_ce;

reg ap_idle;
reg p_pred_0_ap_vld;
reg p_pred_3_ap_vld;
reg p_pred_2_ap_vld;
reg p_pred_1_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_250_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln35_fu_262_p1;
reg   [63:0] zext_ln35_reg_385;
reg   [63:0] zext_ln35_reg_385_pp0_iter1_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter2_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter3_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter4_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter5_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter6_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter7_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter8_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter9_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter10_reg;
reg   [63:0] zext_ln35_reg_385_pp0_iter11_reg;
wire   [1:0] trunc_ln35_fu_267_p1;
reg   [1:0] trunc_ln35_reg_392;
reg   [1:0] trunc_ln35_reg_392_pp0_iter1_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter2_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter3_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter4_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter5_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter6_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter7_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter8_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter9_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter10_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter11_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter12_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter13_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter14_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter15_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter16_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter17_reg;
reg   [1:0] trunc_ln35_reg_392_pp0_iter18_reg;
wire   [31:0] bitcast_ln40_4_fu_286_p1;
reg   [31:0] mul_reg_407;
wire   [31:0] tmp_fu_291_p11;
wire   [31:0] bitcast_ln40_5_fu_311_p1;
reg   [31:0] add_reg_427;
reg   [31:0] mul_1_reg_432;
wire   [31:0] bitcast_ln40_6_fu_316_p1;
reg   [31:0] add23_1_reg_447;
reg   [31:0] mul_2_reg_452;
wire   [31:0] bitcast_ln40_7_fu_321_p1;
reg   [31:0] add23_2_reg_467;
reg   [31:0] mul_3_reg_472;
wire    ap_block_pp0_stage0;
reg   [2:0] i_fu_78;
wire   [2:0] add_ln35_fu_256_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_1;
wire   [31:0] bitcast_ln40_8_fu_326_p1;
wire    ap_block_pp0_stage0_01001;
reg    A_0_ce0_local;
reg    A_1_ce0_local;
reg    A_2_ce0_local;
reg    A_3_ce0_local;
wire   [31:0] tmp_fu_291_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_block_pp0_stage0_00001;
wire   [1:0] tmp_fu_291_p1;
wire   [1:0] tmp_fu_291_p3;
wire  signed [1:0] tmp_fu_291_p5;
wire  signed [1:0] tmp_fu_291_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 i_fu_78 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) predict_kernel_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U9(
    .din0(bitcast_ln37),
    .din1(bitcast_ln37_1),
    .din2(bitcast_ln37_2),
    .din3(bitcast_ln37_3),
    .def(tmp_fu_291_p9),
    .sel(trunc_ln35_reg_392_pp0_iter3_reg),
    .dout(tmp_fu_291_p11)
);

predict_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter18_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln35_fu_250_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_78 <= add_ln35_fu_256_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_78 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add23_1_reg_447 <= grp_fu_386_p_dout0;
        add23_2_reg_467 <= grp_fu_390_p_dout0;
        add_reg_427 <= grp_fu_382_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul_1_reg_432 <= grp_fu_402_p_dout0;
        mul_2_reg_452 <= grp_fu_406_p_dout0;
        mul_3_reg_472 <= grp_fu_410_p_dout0;
        mul_reg_407 <= grp_fu_398_p_dout0;
        trunc_ln35_reg_392_pp0_iter10_reg <= trunc_ln35_reg_392_pp0_iter9_reg;
        trunc_ln35_reg_392_pp0_iter11_reg <= trunc_ln35_reg_392_pp0_iter10_reg;
        trunc_ln35_reg_392_pp0_iter12_reg <= trunc_ln35_reg_392_pp0_iter11_reg;
        trunc_ln35_reg_392_pp0_iter13_reg <= trunc_ln35_reg_392_pp0_iter12_reg;
        trunc_ln35_reg_392_pp0_iter14_reg <= trunc_ln35_reg_392_pp0_iter13_reg;
        trunc_ln35_reg_392_pp0_iter15_reg <= trunc_ln35_reg_392_pp0_iter14_reg;
        trunc_ln35_reg_392_pp0_iter16_reg <= trunc_ln35_reg_392_pp0_iter15_reg;
        trunc_ln35_reg_392_pp0_iter17_reg <= trunc_ln35_reg_392_pp0_iter16_reg;
        trunc_ln35_reg_392_pp0_iter18_reg <= trunc_ln35_reg_392_pp0_iter17_reg;
        trunc_ln35_reg_392_pp0_iter2_reg <= trunc_ln35_reg_392_pp0_iter1_reg;
        trunc_ln35_reg_392_pp0_iter3_reg <= trunc_ln35_reg_392_pp0_iter2_reg;
        trunc_ln35_reg_392_pp0_iter4_reg <= trunc_ln35_reg_392_pp0_iter3_reg;
        trunc_ln35_reg_392_pp0_iter5_reg <= trunc_ln35_reg_392_pp0_iter4_reg;
        trunc_ln35_reg_392_pp0_iter6_reg <= trunc_ln35_reg_392_pp0_iter5_reg;
        trunc_ln35_reg_392_pp0_iter7_reg <= trunc_ln35_reg_392_pp0_iter6_reg;
        trunc_ln35_reg_392_pp0_iter8_reg <= trunc_ln35_reg_392_pp0_iter7_reg;
        trunc_ln35_reg_392_pp0_iter9_reg <= trunc_ln35_reg_392_pp0_iter8_reg;
        zext_ln35_reg_385_pp0_iter10_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter9_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter11_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter10_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter2_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter1_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter3_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter2_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter4_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter3_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter5_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter4_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter6_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter5_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter7_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter6_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter8_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter7_reg[2 : 0];
        zext_ln35_reg_385_pp0_iter9_reg[2 : 0] <= zext_ln35_reg_385_pp0_iter8_reg[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln35_reg_392 <= trunc_ln35_fu_267_p1;
        trunc_ln35_reg_392_pp0_iter1_reg <= trunc_ln35_reg_392;
        zext_ln35_reg_385[2 : 0] <= zext_ln35_fu_262_p1[2 : 0];
        zext_ln35_reg_385_pp0_iter1_reg[2 : 0] <= zext_ln35_reg_385[2 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        A_0_ce0_local = 1'b1;
    end else begin
        A_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        A_1_ce0_local = 1'b1;
    end else begin
        A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        A_2_ce0_local = 1'b1;
    end else begin
        A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        A_3_ce0_local = 1'b1;
    end else begin
        A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_250_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter18_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter19 == 1'b1) & (trunc_ln35_reg_392_pp0_iter18_reg == 2'd0))) begin
        p_pred_0_ap_vld = 1'b1;
    end else begin
        p_pred_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter19 == 1'b1) & (trunc_ln35_reg_392_pp0_iter18_reg == 2'd1))) begin
        p_pred_1_ap_vld = 1'b1;
    end else begin
        p_pred_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter19 == 1'b1) & (trunc_ln35_reg_392_pp0_iter18_reg == 2'd2))) begin
        p_pred_2_ap_vld = 1'b1;
    end else begin
        p_pred_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter19 == 1'b1) & (trunc_ln35_reg_392_pp0_iter18_reg == 2'd3))) begin
        p_pred_3_ap_vld = 1'b1;
    end else begin
        p_pred_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_0_address0 = zext_ln35_fu_262_p1;

assign A_0_ce0 = A_0_ce0_local;

assign A_1_address0 = zext_ln35_reg_385_pp0_iter3_reg;

assign A_1_ce0 = A_1_ce0_local;

assign A_2_address0 = zext_ln35_reg_385_pp0_iter7_reg;

assign A_2_ce0 = A_2_ce0_local;

assign A_3_address0 = zext_ln35_reg_385_pp0_iter11_reg;

assign A_3_ce0 = A_3_ce0_local;

assign add_ln35_fu_256_p2 = (ap_sig_allocacmp_i_1 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln40_4_fu_286_p1 = A_0_q0;

assign bitcast_ln40_5_fu_311_p1 = A_1_q0;

assign bitcast_ln40_6_fu_316_p1 = A_2_q0;

assign bitcast_ln40_7_fu_321_p1 = A_3_q0;

assign bitcast_ln40_8_fu_326_p1 = grp_fu_394_p_dout0;

assign grp_fu_382_p_ce = 1'b1;

assign grp_fu_382_p_din0 = tmp_fu_291_p11;

assign grp_fu_382_p_din1 = mul_reg_407;

assign grp_fu_382_p_opcode = 2'd0;

assign grp_fu_386_p_ce = 1'b1;

assign grp_fu_386_p_din0 = add_reg_427;

assign grp_fu_386_p_din1 = mul_1_reg_432;

assign grp_fu_386_p_opcode = 2'd0;

assign grp_fu_390_p_ce = 1'b1;

assign grp_fu_390_p_din0 = add23_1_reg_447;

assign grp_fu_390_p_din1 = mul_2_reg_452;

assign grp_fu_390_p_opcode = 2'd0;

assign grp_fu_394_p_ce = 1'b1;

assign grp_fu_394_p_din0 = add23_2_reg_467;

assign grp_fu_394_p_din1 = mul_3_reg_472;

assign grp_fu_394_p_opcode = 2'd0;

assign grp_fu_398_p_ce = 1'b1;

assign grp_fu_398_p_din0 = bitcast_ln40_4_fu_286_p1;

assign grp_fu_398_p_din1 = bitcast_ln40;

assign grp_fu_402_p_ce = 1'b1;

assign grp_fu_402_p_din0 = bitcast_ln40_5_fu_311_p1;

assign grp_fu_402_p_din1 = bitcast_ln40_1;

assign grp_fu_406_p_ce = 1'b1;

assign grp_fu_406_p_din0 = bitcast_ln40_6_fu_316_p1;

assign grp_fu_406_p_din1 = bitcast_ln40_2;

assign grp_fu_410_p_ce = 1'b1;

assign grp_fu_410_p_din0 = bitcast_ln40_7_fu_321_p1;

assign grp_fu_410_p_din1 = bitcast_ln40_3;

assign icmp_ln35_fu_250_p2 = ((ap_sig_allocacmp_i_1 == 3'd4) ? 1'b1 : 1'b0);

assign p_pred_0 = bitcast_ln40_8_fu_326_p1;

assign p_pred_1 = bitcast_ln40_8_fu_326_p1;

assign p_pred_2 = bitcast_ln40_8_fu_326_p1;

assign p_pred_3 = bitcast_ln40_8_fu_326_p1;

assign tmp_fu_291_p9 = 'bx;

assign trunc_ln35_fu_267_p1 = ap_sig_allocacmp_i_1[1:0];

assign zext_ln35_fu_262_p1 = ap_sig_allocacmp_i_1;

always @ (posedge ap_clk) begin
    zext_ln35_reg_385[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter1_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter2_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter3_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter4_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter5_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter6_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter7_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter8_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter9_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter10_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_385_pp0_iter11_reg[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //predict_kernel_predict_kernel_Pipeline_VITIS_LOOP_35_1
